module Prophet

include("make_holidays.jl")
include("stan_backend.jl")
include("turing/prophet-turing.jl")
include("turing/neural_prophet.jl")
include("plot.jl")
include("forecaster_api.jl")
include("diagnostics.jl")

export ProphetModel,
       add_country_holidays,
       add_country_holidays!,
       add_regressor,
       add_regressor!,
       add_seasonality,
       add_seasonality!,
       set_model_backend,
       set_model_backend!,
       model_backend,
       fit,
       predict,
       make_future_dataframe,
       setup_dataframe,
       initialize_scales!,
       linear_growth_init,
       logistic_growth_init,
       flat_growth_init,
       piecewise_linear,
       piecewise_logistic,
       generate_cutoffs,
       cross_validation,
       single_cutoff_forecast,
       performance_metrics,
       mse,
       rmse,
       mae,
       mape,
       mdape,
       smape,
       coverage,
       fourier_series,
       make_seasonality_features,
       construct_holiday_dataframe,
       make_holiday_features,
       get_holiday_names,
       make_holidays_df,
       supported_holiday_countries,
       stan_model_file,
       stan_backend_module,
       cmdstan_home,
       cmdstan_stanc,
       cmdstan_version,
       REQUIRED_CMDSTAN_VERSION,
       get_changepoint_matrix,
       logistic_gamma,
       logistic_trend,
       linear_trend,
       flat_trend,
       prophet_mean,
       NeuralProphetNN,
       neural_prophet_mean,
       prophet,
       neural_prophet,
       plot_forecast,
       plot_forecast_component

end
